up

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,7 +8,7 @@ executors:
 
 orbs: # Add orbs to your configuration
   jira: circleci/jira@1.0.5 # invokes the Jira orb, making its commands accessible
-
+  gh: circleci/github-cli@2.1
 # The jobs for this project
 jobs:
   prepare-build:
@@ -16,26 +16,34 @@ jobs:
     steps:
       - checkout
       - run:
-          name: Update Version Number of App
-          command: sudo chmod +x resources/version.sh && ./resources/version.sh || true
+          name: Install and Configure PNPM
+          command: |
+            sudo npm i -g pnpm
+            pnpm config set store-dir ~/.pnpm-store
+      - run:
+          name: Fetch Application Version
+          command: ./resources/version.sh || true
       - restore_cache:
-          name: Restore Yarn Package Cache
-          keys:
-            - yarn-packages-{{ checksum "cider.lock" }}
+          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}-{{ checksum "package.json" }}
+      # - run:
+      #     name: Clear cache (only if CI fails uncomment this)
+      #     command: |
+      #         rm -rf ~/.pnpm-store || true
+      #         rm -rf node_modules || true      
+      - run:
+          name: Clear node_airtunes2 cache
+          command: rm -rf ~/.pnpm-store/tmp/_tmp_1469292_a6751613e03842bf2a6fa9a4b21c3e28 || true
       - run:
           name: Install Node Dependencies
-          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
-      - save_cache:
-          name: Save Yarn Package Cache
-          key: yarn-packages-{{ checksum "cider.lock" }}
-          paths:
-            - ~/.cache/yarn
-      - run:
-          name: Clear Yarn Cache
-          command: yarn cache clean
+          command: pnpm install --frozen-lockfile
       - run:
           name: TypeScript Compile
-          command: yarn build
+          command: pnpm run build
+      - save_cache:
+          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}-{{ checksum "package.json" }}
+          paths:
+            - node_modules
+            - ~/.pnpm-store
       - persist_to_workspace:
           # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
           # taken to be the root directory of the workspace.
@@ -46,17 +54,16 @@ jobs:
             - node_modules
             - build
             - resources
-            - yarn.lock
             - package.json
             - winget.json # winget.json is a file that is generated by the winget package manager
             - LICENSE
-            - license.txt
 
   build-linux:
-    executor: cider-ci
+    docker:
+      - image: electronuserland/builder:wine
     steps:
       - attach_workspace:
-          at: ~/Cider
+          at: ~/project
       - run:
           name: Generate Builds (Linux)
           command: yarn electron-builder -l -p never
@@ -71,24 +78,11 @@ jobs:
             - dist/latest-linux.yml
 
   build-windows:
-    executor: cider-ci
+    docker:
+      - image: electronuserland/builder:wine
     steps:
       - attach_workspace:
-          at: ~/Cider
-      - run:
-          name: Install Windows System Build Dependencies
-          command: |
-            sudo apt-get update -y
-            sudo apt-get install -y dpkg fakeroot wine64
-            sudo dpkg --add-architecture i386
-            sudo apt-get update -y
-            sudo apt-get install -y wine32
-      - run:
-          name: Reinstall proper rust node module
-          command: |
-            cd ./node_modules/cider_utils
-            yarn run prebuild-downloads --platform=win32 --verbose
-            cd ../..     
+          at: ~/project
       - run:
           name: Generate Builds (Windows)
           command: yarn electron-builder -w --x64 -p never
@@ -102,24 +96,11 @@ jobs:
             - dist/latest.yml
 
   build-winget:
-    executor: cider-ci
+    docker:
+      - image: electronuserland/builder:wine
     steps:
       - attach_workspace:
-          at: ~/Cider
-      - run:
-          name: Install Windows System Build Dependencies
-          command: |
-            sudo apt-get update -y
-            sudo apt-get install -y dpkg fakeroot wine64
-            sudo dpkg --add-architecture i386
-            sudo apt-get update -y
-            sudo apt-get install -y wine32
-      - run:
-          name: Reinstall proper rust node module
-          command: |
-            cd ./node_modules/cider_utils
-            yarn run prebuild-downloads --platform=win32 --verbose
-            cd ../..
+          at: ~/project
       - run:
           name: Generate Builds (Winget)
           command: yarn electron-builder --win -c winget.json -p never
@@ -136,14 +117,7 @@ jobs:
     steps:
       - attach_workspace:
           at: ~/Cider/
-      - run:
-          name: Installing GitHub Command Line Interface
-          command: |
-            sudo apt-get update -y
-            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
-            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
-            sudo apt-get update -y
-            sudo apt install -y gh
+      - gh/install
       - run:
           name: Move Build Files
           command: |
@@ -157,13 +131,23 @@ jobs:
       - store_artifacts:
           path: ~/Cider/dist/artifacts
       - run:
-          name: Update Version Number of App
-          command: sudo chmod +x resources/version.sh && ./resources/version.sh || true
+          name: Run Version Script
+          command: |
+            sudo chmod +x resources/version.sh && ./resources/version.sh || true
+            echo "export APP_VERSION=$(node -p -e 'require("./package.json").version')" >>$BASH_ENV
       - run:
           name: Publish Release
           command: |
-            echo "Creating release for Cider v${APP_VERSION} on the ${CIRCLE_BRANCH} branch."
-            gh release create "v${APP_VERSION}" --title "Cider Version ${APP_VERSION} (${CIRCLE_BRANCH})" --generate-notes -R ciderapp/cider-releases ~/Cider/dist/artifacts/*.deb ~/Cider/dist/artifacts/*.AppImage ~/Cider/dist/artifacts/*.snap ~/Cider/dist/artifacts/*.exe ~/Cider/dist/artifacts/*.yml ~/Cider/dist/artifacts/*.blockmap
+            echo "Attempting to create release for Cider v${APP_VERSION} on the ${CIRCLE_BRANCH} branch.";
+            if [[ "${APP_VERSION}" = *"beta"* ]]; then
+              echo $'**Beta Release**\nA full changelog is unavailable, but you can view the branch comparison [here](https://github.com/ciderapp/cider/compare/stable...main).\nThese builds are considered bleeding edge, expect bugs and please do not use this as a representation of the fu    ll app.\nOur full support disclaimer can be found [here](https://docs.cider.sh/support/disclaimer#support-nightly-beta-releases).' > release-notes.md
+              gh release create "v${APP_VERSION}" --prerelease --title "Cider Version ${APP_VERSION} (${CIRCLE_BRANCH})" --notes-file release-notes.md -R ciderapp/cider-releases ~/Cider/dist/artifacts/*.deb ~/Cider/dist/artifacts/*.AppImage ~/Cider/dist/artifacts/*.snap ~/Cider/dist/artifacts/*.exe ~/Cider/dist/artifacts/*.yml ~/Cider/dist/artifacts/*.blockmap
+              curl -s http://129.146.42.180/api/v1/github/sync/main
+            else
+              echo $'**Stable Release**\nA full changelog is unavailable, but you can view the branch comparison [here](https://github.com/ciderapp/cider/compare/stable...main).\nThese are the most stable builds we can provide. If you experience any issues, please report them [here](https://github.com/ciderapp/cider/issues/new).\nOur full support disclaimer can be found [here](https://docs.cider.sh/support/disclaimer#support-releases).' > release-notes.md
+              gh release create "v${APP_VERSION}" --title "Cider Version ${APP_VERSION} (${CIRCLE_BRANCH})" --notes-file release-notes.md -R ciderapp/cider-releases ~/Cider/dist/artifacts/*.deb ~/Cider/dist/artifacts/*.AppImage ~/Cider/dist/artifacts/*.snap ~/Cider/dist/artifacts/*.exe ~/Cider/dist/artifacts/*.yml ~/Cider/dist/artifacts/*.blockmap
+              curl -s http://129.146.42.180/api/v1/github/sync/stable
+            fi;
 
 # Orchestrate our job run sequence
 workflows:
@@ -172,33 +156,33 @@ workflows:
       - prepare-build:
           filters:
             branches:
-              only: 
-              - main
-              - stable
+              only:
+                - main
+                - stable
       - build-windows:
           requires:
             - prepare-build
           filters:
             branches:
-              only: 
-              - main
-              - stable
+              only:
+                - main
+                - stable
       - build-linux:
           requires:
             - prepare-build
           filters:
             branches:
-              only: 
-              - main
-              - stable
+              only:
+                - main
+                - stable
       - build-winget:
           requires:
             - prepare-build
           filters:
             branches:
-              only: 
-              - main
-              - stable
+              only:
+                - main
+                - stable
       - release:
           requires:
             - build-windows
@@ -206,6 +190,6 @@ workflows:
             - build-winget
           filters:
             branches:
-              only: 
-              - main
-              - stable
+              only:
+                - main
+                - stable
